id = "lumen-icons"
name = "Lumen Icons"
version = "0.1.0"
schema_version = 1
authors = ["Cleidy cleidydev@gmail.com"]
description = "Lumen icons para o Zed"
repository = "https://github.com/cleidyDev/zed-materia-theme"
